/* goal.io — stadium props.

   Corner flags, floodlight pylons and dugouts, from
   assets/models/stadium_props.glb, generated by tools/blender/stadium_props.py.

   WHY THIS EXISTS
   ---------------
   The bowl in js/render.gl.js is parametric and good — rake, gangways,
   hoardings, roof, 18,000 spectators. What it had none of is *objects*, and a
   ground reads as a ground because of the clutter around the pitch.

   Corner flags are the sharp case: the canvas renderer drew them, and
   drawCornerFlags() was one of the passes js/render.gl.js stubbed out when it
   took the world over. Nothing replaced it. They have been missing from the
   game entirely since — on the pitch, in shot, every match.

   HOW IT ATTACHES
   ---------------
   Same shape as js/skin.gl.js: its own program compiled from GLR.glsl so it is
   lit by the same rig as everything else, its own boot, and two hooks in
   render.gl.js. If the GLB does not load, nothing here runs and the game is
   exactly what it was.

   PLACEMENT IS DERIVED, NOT TYPED
   -------------------------------
   Every position comes from PITCH and the bowl's own geometry, so changing
   config/pitch.json moves the flags and the dugouts with the lines. A table of
   hand-typed metres would be correct once and wrong after the first edit.
*/
"use strict";

var PROPS = (function () {

  var gl = null;
  var ready = false, failed = false;
  var P = null, PDEPTH = null;
  var MESHES = {};             // prop name -> {mesh, tint, rough, metal}
  var PLACED = [];             // {name, x, y, yaw, scale}

  var URL = "assets/models/stadium_props.glb";

  function flagged() {
    try { return !/[?&]props=0/.test(location.search); } catch (e) { return true; }
  }

  /* ==================================================================== */
  /* shaders                                                               */
  /* ==================================================================== */

  function shaders() {
    var G = (typeof GLR !== "undefined" && GLR.glsl) ? GLR.glsl : null;
    if (!G) return null;

    var VS = G.HEAD + `
    in vec3 aPos;
    in vec3 aNrm;
    uniform mat4 uVP, uModel;
    uniform mat3 uNrm;
    out vec3 vW, vN;
    void main() {
      vec4 w = uModel * vec4(aPos, 1.0);
      vW = w.xyz;
      vN = normalize(uNrm * aNrm);
      gl_Position = uVP * w;
    }
    `;

    var FS = G.HEAD + G.COMMON + G.PBR + G.SHADOW + `
    in vec3 vW, vN;
    out vec4 oCol;
    uniform vec3 uTint;
    uniform vec2 uMR;          // roughness, metallic
    uniform float uEmissive;   // floodlight lamps read as lit, not as grey boxes
    void main() {
      vec3 n = normalize(vN);
      vec3 V = normalize(uEye - vW);
      float ndl = dot(n, uLight);
      float sh = shadowAt(vW + n * 0.04, ndl);
      /* props stand on the ground, so the same height-based contact term the
         players use keeps their feet from floating */
      float ao = mix(0.72, 1.0, clamp(vW.z / 2.2, 0.0, 1.0));
      vec3 lit = surfacePBR(vW, n, V, uTint, uMR.x, uMR.y, ao, sh);
      /* The lamps are the only emissive surface in the game. Tied to the
         condition's flood value so they are dark on a Sunday afternoon and
         burning at night, which is the whole reason a pylon is worth drawing. */
      lit += vec3(1.0, 0.97, 0.88) * uEmissive * uCond.z;
      lit = grade(lit);
      oCol = vec4(applyFog(lit, length(uEye - vW)), 1.0);
    }
    `;

    var DFS = G.HEAD + `
    out vec4 oCol;
    void main() { oCol = vec4(1.0); }
    `;

    return { VS: VS, FS: FS, DFS: DFS };
  }

  /* ==================================================================== */
  /* placement — all of it derived from the pitch                          */
  /* ==================================================================== */

  function place() {
    PLACED = [];
    var hw = PITCH.halfW, hl = PITCH.halfL;

    /* Corner flags, one per corner, each canted slightly out of the pitch the
       way a real one leans away from play. */
    [[-1, -1], [1, -1], [-1, 1], [1, 1]].forEach(function (s) {
      PLACED.push({
        name: "Prop_CornerFlag",
        x: s[0] * hw, y: s[1] * hl,
        yaw: Math.atan2(-s[1], -s[0]),      // flag faces in toward the centre
        scale: 1
      });
    });

    /* Floodlights at the four corners of the bowl, outside the stand. The
       radius comes from the bowl's own footprint rather than a typed number,
       so widening the surround moves the pylons with it. */
    var SUR = (typeof SURROUND !== "undefined") ? SURROUND : 6;
    var px = hw + SUR + 26, py = hl + SUR + 26;
    [[-1, -1], [1, -1], [-1, 1], [1, 1]].forEach(function (s) {
      PLACED.push({
        name: "Prop_Floodlight",
        x: s[0] * px, y: s[1] * py,
        /* the head is tilted toward the pitch, so the pylon has to face the
           centre spot or it lights the car park */
        yaw: Math.atan2(-s[1] * py, -s[0] * px),
        scale: 1
      });
    });

    /* Two dugouts on the near touchline, either side of the halfway line, set
       back into the surround so they are off the pitch. */
    [-1, 1].forEach(function (s) {
      PLACED.push({
        name: "Prop_Dugout",
        x: s * 9.5, y: hl + 4.2,
        yaw: -Math.PI / 2,                  // opening faces the pitch
        scale: 1
      });
    });
  }

  /* ==================================================================== */
  /* draw                                                                  */
  /* ==================================================================== */

  var mModel = new Float32Array(16);
  var nrm3 = new Float32Array(9);

  /* glTF is Y-up and faces +Z; the game is Z-up and faces +F. Same basis map
     js/skin.gl.js uses for characters, for the same reason — one convention,
     written down once. */
  function modelMatrix(p) {
    var c = Math.cos(p.yaw), s = Math.sin(p.yaw), k = p.scale || 1;
    var Fx = c, Fy = s;                 // forward
    var Rx = s, Ry = -c;                // right
    mModel[0] = -Rx * k; mModel[1] = -Ry * k; mModel[2] = 0;    mModel[3] = 0;
    mModel[4] = 0;       mModel[5] = 0;       mModel[6] = k;    mModel[7] = 0;
    mModel[8] = Fx * k;  mModel[9] = Fy * k;  mModel[10] = 0;   mModel[11] = 0;
    mModel[12] = p.x;    mModel[13] = p.y;    mModel[14] = 0;   mModel[15] = 1;

    nrm3[0] = -Rx; nrm3[1] = -Ry; nrm3[2] = 0;
    nrm3[3] = 0;   nrm3[4] = 0;   nrm3[5] = 1;
    nrm3[6] = Fx;  nrm3[7] = Fy;  nrm3[8] = 0;
    return mModel;
  }

  function draw(depthOnly, lightVP, camX, camY) {
    if (!ready) return;
    var prg = depthOnly ? PDEPTH : P;
    if (!prg) return;
    GLX.use(prg);
    if (depthOnly) {
      gl.uniformMatrix4fv(prg.u.uVP, false, lightVP);
    } else if (typeof GLR !== "undefined" && GLR.bindCommon) {
      GLR.bindCommon(prg);
    }

    for (var i = 0; i < PLACED.length; i++) {
      var p = PLACED[i], m = MESHES[p.name];
      if (!m) continue;

      /* A 28 m pylon sits 90 m from the pitch and is nowhere near the shadow
         camera's 22 m box, so putting it in the depth pass costs a draw and
         casts nothing. Flags and dugouts are close enough to matter. */
      if (depthOnly && p.name === "Prop_Floodlight") continue;

      gl.uniformMatrix4fv(prg.u.uModel, false, modelMatrix(p));
      if (!depthOnly) {
        gl.uniformMatrix3fv(prg.u.uNrm, false, nrm3);
        gl.uniform3f(prg.u.uTint, m.tint[0], m.tint[1], m.tint[2]);
        gl.uniform2f(prg.u.uMR, m.rough, m.metal);
        gl.uniform1f(prg.u.uEmissive, m.emissive || 0);
      }
      GLX.draw(m.mesh);
    }
  }

  /* ==================================================================== */
  /* boot                                                                  */
  /* ==================================================================== */

  function boot(glctx) {
    if (failed || ready) return ready;
    if (!flagged()) return false;
    if (typeof GLTF === "undefined" || typeof GLX === "undefined") return false;

    gl = glctx;
    var src = shaders();
    if (!src) return false;
    P = GLX.prog("props", src.VS, src.FS);
    PDEPTH = GLX.prog("propsDepth", src.VS, src.DFS);
    if (!P || !PDEPTH) { failed = true; return false; }

    GLTF.load(URL).then(function (model) {
      /* one mesh per prop, and the mesh order matches the node order the
         exporter wrote, so pair them up by index */
      model.meshes.forEach(function (mesh, i) {
        var prim = mesh.prims[0];
        if (!prim) return;
        var mat = model.materials[prim.material] || {};
        var name = NAMES[i] || mesh.name;
        MESHES[name] = {
          mesh: GLX.mesh(P, [
            { name: "aPos", size: 3, data: prim.pos },
            { name: "aNrm", size: 3, data: prim.nrm }
          ], prim.idx),
          tint: mat.baseColor || [0.6, 0.6, 0.6, 1],
          rough: mat.roughness == null ? 0.7 : mat.roughness,
          metal: mat.metallic == null ? 0 : mat.metallic,
          emissive: name === "Prop_Floodlight" ? 0.55 : 0
        };
      });
      place();
      ready = Object.keys(MESHES).length > 0;
      console.info("[props] " + Object.keys(MESHES).join(", ") +
                   " -> " + PLACED.length + " placed");
    }).catch(function (e) {
      failed = true;
      console.warn("[props] not loaded, stadium stays bare:", e.message);
    });
    return true;
  }

  /* The exporter names the MESH datablocks (Cylinder, Cube.015...) but the
     NODES carry the prop names. The loader reads meshes, so the mapping is by
     index — declared here rather than guessed, and asserted by the count. */
  var NAMES = ["Prop_CornerFlag", "Prop_Dugout", "Prop_Floodlight"];

  return {
    boot: boot,
    draw: draw,
    replace: place,
    get ready() { return ready; },
    get enabled() { return ready && !failed; },
    stats: function () {
      return { ready: ready, failed: failed,
               meshes: Object.keys(MESHES), placed: PLACED.length };
    }
  };
})();
