"""goal.io — bundle config/*.json into a single synchronous script.

WHY THERE IS A BUILD STEP AT ALL, IN A PROJECT THAT HAS NONE
------------------------------------------------------------
The config has to be applied before game.js's boot IIFE runs, because that
calls startLevel() and builds the level grid. fetch() is asynchronous, so a
config loaded that way arrives after the game has already read the built-in
values, and the first match of a session would silently use the wrong data.

Making the JSON load synchronously is not possible without either a blocking
XHR (deprecated, jank) or restructuring the boot sequence (risky, and it would
touch game.js, which is the file most likely to be edited by someone else).

So the JSON stays canonical — diffable, validatable, and what the CMS reads and
writes — and this emits one plain <script> the browser loads in document order
like every other file in the project. The bundle is committed, so a checkout
still needs no toolchain: this only runs when the config changes.

    python tools/config_build.py

Writes config/config.bundle.js. Run tools/config_validate.py first.
"""

import json
import os
import sys
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG = os.path.join(HERE, "config")
OUT = os.path.join(CONFIG, "config.bundle.js")

# order matters only for readability; the loader keys off the names
FILES = ["pitch", "physics", "conditions", "difficulty", "levels", "ui", "audio",
         "kits", "kit-layout"]


def strip_notes(o):
    """$note keys are documentation for whoever opens the JSON. They must not
    reach the game — a stray $note on PITCH would end up iterated over."""
    if isinstance(o, dict):
        return {k: strip_notes(v) for k, v in o.items() if k != "$note"}
    if isinstance(o, list):
        return [strip_notes(v) for v in o]
    return o


def build():
    bundle = {}
    for name in FILES:
        path = os.path.join(CONFIG, name + ".json")
        if not os.path.exists(path):
            print(f"  ! missing {name}.json — skipping")
            continue
        with open(path, encoding="utf-8") as f:
            bundle[name] = strip_notes(json.load(f))
        print(f"  + {name}.json")

    body = json.dumps(bundle, separators=(",", ":"), ensure_ascii=False)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    js = (
        "/* GENERATED by tools/config_build.py — do not edit.\n"
        "   Source of truth is config/*.json. Edit those, then re-run:\n"
        "       python tools/config_build.py\n"
        f"   Built {stamp} from {len(bundle)} file(s). */\n"
        "window.GOALIO_CONFIG = " + body + ";\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(js)
    return len(js), len(bundle)


if __name__ == "__main__":
    print("building config bundle")
    size, n = build()
    print(f"\nconfig/config.bundle.js  {size:,} bytes from {n} file(s)")
    if size > 400_000:
        print("WARNING: bundle is large; it is parsed on every cold start.")
        sys.exit(0)
